# -*- coding: utf-8 -*-
"""Detección de neologismos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xgduDZjQ_HIF9fz_xCfnNqvxyjH7TEw-

# Librerias necesarias para el funcionamiento
"""

import gdown

print("Descargando archivos CSV...")


#tóxico archivos csv

output_to = "toxico_2011.csv" #toxico_2011.csv
id_to ="1gmV34z9n5URFOHBbbWtP-eNLjLWdtXNE"
gdown.download(id=id_to, output=output_to)
output_tn = "toxico_2022.csv" #toxico_2022.csv
id_tn = "1YdSD8firXalyWeepu0hwuGCYo5EDj47v"
gdown.download(id=id_tn, output=output_tn)
print("Archivos de Tóxico : Completado")

#unicornio archivos csv

output_uo = "unicornio_2011.csv"
id_uo = "10YiOpKeUswK74jijk2Go34cLVfN8pNa2" #unicornio_2011.csv
gdown.download(id=id_uo, output=output_uo)
output_un = "unicornio_2022.csv"
id_un = "1RG_7b4IiKXR_bkH3KQTvzsajCyQmKuYh" #unicornio_2022.csv
gdown.download(id=id_un, output=output_un)
print("Archivos de Unicornio : Completado")

#hibernar archivos csv

output_ho = "hibernar_2011.csv"
id_ho = "1xboi6KBAuQx-Fe8iM0GVQ7i3BlNcfAMR"#hibernar_2011.csv
gdown.download(id=id_ho, output=output_ho)
output_hn = "hibernar_2022.csv"
id_hn = "1pxrNqFVR4QDcu1VlUFdbnHeGyroDNqa9" #hibernar_2022.csv
gdown.download(id=id_hn, output=output_hn)
print("Archivos de Hibernar : Completado")


print("Fin!")